sudo: false
language: cpp
os:
  - osx
compiler:
  - clang

addons:
   apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
      packages: ['clang-3.6' , 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'gflags']
env:
  - JOB_NAME=unittests ROCKSDBTESTS_START=db_test ROCKSDBTESTS_END=dbtest_2
  - JOB_NAME=unittests ROCKSDBTESTS_START=db_block_cache_test
  - JOB_NAME=java_test
  - JOB_NAME=lite_build

before_script:
  # Limit the maximum number of open file descriptors to 2000
  - ulimit -n 2000 || true

script:
  - if [[ "${JOB_NAME}" == 'unittests' ]]; then OPT=-DTRAVIS V=1 make -j8 check_some; fi
  - if [[ "${JOB_NAME}" == 'java_test' ]]; then OPT=-DTRAVIS V=1 make clean jclean rocksdbjava jtest; fi
  - if [[ "${JOB_NAME}" == 'lite_build' ]]; then OPT="-DTRAVIS -DROCKSDB_LITE" V=1 make -j8 static_lib; fi
notifications:
    webhooks:
      - https://buildtimetrend.herokuapp.com/travis
